<?php

namespace Database\Seeders;

use App\Models\CategorieDocument;
use App\Models\Document;
use App\Models\User;
use Illuminate\Database\Seeder;

class DocumentSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::inRandomOrder()->first();

        $categorieByNom = fn (string $nom) => CategorieDocument::where('nom', $nom)->first()?->id;

        // Fichier d'exemple utilisé pour tous les documents téléchargeables
        $fichierExemple = 'documents/exemple.pdf';

        $documents = [
            [
                'categorie_id' => $categorieByNom('Rapports annuels'),
                'titre' => 'Rapport annuel 2025 de l\'ENEF',
                'description' => 'Bilan des activités pédagogiques, administratives et financières de l\'École Nationale des Eaux et Forêts pour l\'année 2025.',
                'type' => 'rapport',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 2450,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-RA-001',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(2),
            ],
            [
                'categorie_id' => $categorieByNom('Rapports annuels'),
                'titre' => 'Rapport annuel 2024 de l\'ENEF',
                'description' => 'Bilan des activités pédagogiques, administratives et financières de l\'année 2024.',
                'type' => 'rapport',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 2310,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-RA-002',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subYear(),
            ],
            [
                'categorie_id' => $categorieByNom('Rapports d\'activités'),
                'titre' => 'Rapport d\'activités du premier semestre 2026',
                'description' => 'Point d\'étape sur les formations initiales et continues dispensées entre janvier et juin 2026.',
                'type' => 'rapport',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 1780,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-RD-001',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subDays(20),
            ],
            [
                'categorie_id' => $categorieByNom('Rapports d\'activités'),
                'titre' => 'Rapport d\'activités du second semestre 2025',
                'description' => 'Synthèse des sessions de formation continue et des prestations d\'appui-conseil réalisées de juillet à décembre 2025.',
                'type' => 'rapport',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 1650,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-RD-002',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(5),
            ],
            [
                'categorie_id' => $categorieByNom('Rapports de mission'),
                'titre' => 'Rapport de mission d\'appui-conseil — Plan d\'aménagement forestier',
                'description' => 'Compte rendu de la mission d\'expertise menée auprès d\'une collectivité territoriale sur l\'aménagement d\'un massif forestier.',
                'type' => 'rapport',
                'fichier_url' => null,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 980,
                'acces' => 'public',
                'telechargeable' => false,
                'code_consultation' => 'DOC-RM-001',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(4),
            ],
            [
                'categorie_id' => $categorieByNom('Rapports de mission'),
                'titre' => 'Rapport de mission — Réhabilitation d\'un site minier',
                'description' => 'Étude de terrain et recommandations techniques pour la réhabilitation environnementale d\'un site minier partenaire.',
                'type' => 'rapport',
                'fichier_url' => null,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 1120,
                'acces' => 'public',
                'telechargeable' => false,
                'code_consultation' => 'DOC-RM-002',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(7),
            ],
            [
                'categorie_id' => $categorieByNom('Brochures'),
                'titre' => 'Brochure de présentation de l\'ENEF',
                'description' => 'Présentation générale de l\'école, de ses filières de formation et de ses conditions d\'admission.',
                'type' => 'brochure',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 890,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-BR-001',
                'version' => '2.1',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(6),
            ],
            [
                'categorie_id' => $categorieByNom('Brochures'),
                'titre' => 'Guide du candidat — Session 2026/2027',
                'description' => 'Modalités de candidature, pièces à fournir et calendrier du concours d\'entrée en formation initiale.',
                'type' => 'brochure',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 654,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-BR-002',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonth(),
            ],
            [
                'categorie_id' => $categorieByNom('Brochures'),
                'titre' => 'Catalogue des formations continues 2026',
                'description' => 'Liste des modules de formation continue proposés aux professionnels de l\'environnement et des ressources naturelles.',
                'type' => 'brochure',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 1240,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-BR-003',
                'version' => '1.1',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(3),
            ],
            [
                'categorie_id' => $categorieByNom('Décrets'),
                'titre' => 'Décret portant organisation de l\'ENEF',
                'description' => 'Texte réglementaire fixant l\'organisation administrative et pédagogique de l\'établissement.',
                'type' => 'texte_reglementaire',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 320,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-DC-001',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subYears(2),
            ],
            [
                'categorie_id' => $categorieByNom('Décrets'),
                'titre' => 'Décret fixant les frais de scolarité et de formation',
                'description' => 'Texte réglementaire encadrant les tarifs applicables à la formation initiale et continue.',
                'type' => 'texte_reglementaire',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 180,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-DC-002',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(18),
            ],
            [
                'categorie_id' => $categorieByNom('Arrêtés'),
                'titre' => 'Arrêté portant nomination des membres du jury du concours 2026',
                'description' => 'Arrêté fixant la composition du jury chargé de la sélection des candidats à la formation initiale.',
                'type' => 'texte_reglementaire',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 210,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-AR-001',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(3),
            ],
            [
                'categorie_id' => $categorieByNom('Arrêtés'),
                'titre' => 'Arrêté portant ouverture du concours d\'entrée 2026/2027',
                'description' => 'Arrêté fixant les conditions, le calendrier et les modalités d\'organisation du concours d\'entrée.',
                'type' => 'texte_reglementaire',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 195,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-AR-002',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(2),
            ],
            [
                'categorie_id' => $categorieByNom('Statuts et règlements'),
                'titre' => 'Règlement intérieur des élèves et stagiaires',
                'description' => 'Ensemble des règles de discipline, d\'assiduité et de vie commune applicables aux élèves et stagiaires de l\'ENEF.',
                'type' => 'texte_reglementaire',
                'fichier_url' => null,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 445,
                'acces' => 'public',
                'telechargeable' => false,
                'code_consultation' => 'DOC-SR-001',
                'version' => '3.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subYear(),
            ],
            [
                'categorie_id' => $categorieByNom('Statuts et règlements'),
                'titre' => 'Statut particulier du personnel enseignant',
                'description' => 'Texte fixant les droits, obligations et grille indiciaire du personnel enseignant de l\'établissement.',
                'type' => 'texte_reglementaire',
                'fichier_url' => null,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 510,
                'acces' => 'public',
                'telechargeable' => false,
                'code_consultation' => 'DOC-SR-002',
                'version' => '2.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(14),
            ],
            [
                'categorie_id' => $categorieByNom('Guides pratiques'),
                'titre' => 'Guide pratique de la gestion des ressources naturelles',
                'description' => 'Support de référence destiné aux stagiaires en formation continue, portant sur les bonnes pratiques de gestion forestière.',
                'type' => 'support_pedagogique',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 3120,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-GP-001',
                'version' => '1.2',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(8),
            ],
            [
                'categorie_id' => $categorieByNom('Guides pratiques'),
                'titre' => 'Guide pratique de l\'inventaire forestier',
                'description' => 'Méthodologie et outils de terrain pour la réalisation d\'un inventaire forestier fiable.',
                'type' => 'support_pedagogique',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 2680,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-GP-002',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(10),
            ],
            [
                'categorie_id' => $categorieByNom('Manuels de cours'),
                'titre' => 'Manuel de formation — SIG et télédétection appliqués',
                'description' => 'Support de cours du module SIG et télédétection, incluant exercices pratiques et études de cas.',
                'type' => 'support_pedagogique',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 4580,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-MC-001',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(5),
            ],
            [
                'categorie_id' => $categorieByNom('Manuels de cours'),
                'titre' => 'Manuel de sylviculture appliquée',
                'description' => 'Support de cours couvrant les techniques de sylviculture et de gestion durable des peuplements forestiers.',
                'type' => 'support_pedagogique',
                'fichier_url' => $fichierExemple,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 3890,
                'acces' => 'public',
                'telechargeable' => true,
                'code_consultation' => 'DOC-MC-002',
                'version' => '1.1',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(9),
            ],
            [
                'categorie_id' => $categorieByNom('Manuels de cours'),
                'titre' => 'Manuel d\'étude d\'impact environnemental',
                'description' => 'Support pédagogique présentant la méthodologie de conduite d\'une étude d\'impact environnemental et social.',
                'type' => 'support_pedagogique',
                'fichier_url' => null,
                'format_fichier' => 'pdf',
                'taille_fichier_ko' => 2950,
                'acces' => 'public',
                'telechargeable' => false,
                'code_consultation' => 'DOC-MC-003',
                'version' => '1.0',
                'nombre_telechargements' => 0,
                'publie_le' => now()->subMonths(11),
            ],
        ];

        foreach ($documents as $document) {
            Document::create([
                ...$document,
                'publie_par' => $user?->id,
            ]);
        }
    }
}